### ISSUE TITLE
Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by DannyBen** [containership/containership.cli#28]
Not sure why this is happening, can provide my config files if will help.

I am getting this error using almost any command (`cs info`, `cs container list`)

```
$ cs app list
/app/node_modules/yargs/yargs.js:1079
      else throw err
           ^

TypeError: Cannot read property 'headers' of undefined
    at requestOptions (/app/lib/request.js:37:64)
    at Object.module.exports.get (/app/lib/request.js:8:19)
    at Object.callback [as handler] (/app/commands/app.js:77:24)
    at Object.self.runCommand (/app/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/app/node_modules/yargs/yargs.js:990:30)
    at Object.self.runCommand (/app/node_modules/yargs/lib/command.js:204:96)
    at Object.Yargs.self._parseArgs (/app/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/app/node_modules/yargs/yargs.js:927:19)
    at ContainershipCli.run (/app/index.js:53:32)
    at Object.<anonymous> (/app/bin/cli.js:3:29)

```

**Comment by nicktate** [comment]
I haven't been able to reproduce on the latest `2.x` client. If you run into this issue in the future, please re-open a ticket and someone will take a deeper dive. It may be useful in the future to have a sanitized version of your local `$HOME/.containership/cli-v2.json` file to debug further.
